### ISSUE TITLE
Header section : Phone number and Contact us menu breaks to next line in Safari

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Spear-Dojo#66]
![18](https://cloud.githubusercontent.com/assets/13309806/13981565/d69245aa-f10a-11e5-94c7-95b7056a49bb.png)

**Comment by asif-titan** [comment]
As per the standards we do not support safari for windows.
I have also confirmed this with Roselie.
[21-03-2016 12:23:22] sowedane asif: do we need to test in safari for windows
[21-03-2016 12:28:17] Seli Sumido: nope, not anymore
