### ISSUE TITLE
w3c errors (Timetable page) : 3 Errors, 1 Warning

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Spear-Dojo#95]
![d2](https://cloud.githubusercontent.com/assets/13309806/14485733/6d12af8a-0176-11e6-9573-03bac18417b7.png)

**Comment by kabirkhan123** [comment]
As the errors are inline styles of plugin files, we have no access to change the plugin files.

**Comment by roseliesromeo** [comment]
Plug-in issue
